acquire:
  scrapy_config:
    USER_AGENT: guess-the-player/1.0 (https://github.com/davidsirait/guess-the-player)
    FEED_URI_PARAMS: tfmkt.utils.uri_params
    FEEDS:
      "data/raw/transfermarkt-scraper/%(season)s/%(name)s.json.gz":
        format: jsonlines
        postprocessing: [scrapy.extensions.postprocessing.GzipPlugin]
    SPIDER_MODULES: ['tfmkt']
    REQUEST_FINGERPRINTER_IMPLEMENTATION: '2.7'
    HTTPCACHE_ENABLED: True

